SELECT EMPLOYEE.NAME FROM EMPLOYEE JOIN 
(SELECT  DEPARTMENT_ID, AVG(SALARY) AS AvgSalary
FROM EMPLOYEE
WHERE CHIEF_ID<>0 
GROUP BY DEPARTMENT_ID)AS AverageSalaryDepartment 
ON 2*AverageSalaryDepartment.AvgSalary<EMPLOYEE.SALARY
 AND
AverageSalaryDepartment.DEPARTMENT_ID=EMPLOYEE.DEPARTMENT_ID

